version: '2'
services:
  # 基本环境
  nginx:
    container_name: "nginx"
    image: nginx
    build: ./nginx
    command: nginx -g 'daemon off;'
    restart: always
    # 数据卷
    volumes:
      - "$PWD/nginx/code:/usr/share/nginx/html"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/nginx_conf.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - 80:80
    networks:
      ssrf:
        ipv4_address: 10.10.1.3

  php:
    container_name: "php"
    # build 该置顶目录下的dockerfile
    build: ./php
    # image指定build Dockerfile生成镜像的名称
    image: php:7.0-fpm-mysqli
    expose:
        - 9000
    volumes:
        - "$PWD/php/code:/var/www/html"
        - "$PWD/php/php.ini:/usr/local/etc/php/php.ini"
    networks:
      ssrf:
        ipv4_address: 10.10.1.5

  vuln-nginx:
    container_name: "vuln-nginx"
    image: nginx
    build: ./vuln-nginx
    command: nginx -g 'daemon off;'
    restart: always
    # 数据卷
    volumes:
      - "$PWD/vuln-nginx/code:/usr/share/nginx/html"
      - "$PWD/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "$PWD/nginx/nginx_conf.conf:/etc/nginx/conf.d/default.conf"
    expose:
        - 80
    networks:
      ssrf:
        ipv4_address: 10.10.1.6



networks:
    # 配置docker network
    ssrf:
      driver: bridge
      ipam:
        config:
          # 子网络
          - subnet: 10.10.1.0/16